import type { Metadata } from "next";
import Link from "next/link";
import fs from "fs";
import path from "path";
import SchemaMarkup from "@/components/SchemaMarkup";
import PhoneCTA from "@/components/PhoneCTA";
import { SITE_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Medicare Guides | MedicareYourself",
  description:
    "Straightforward Medicare guides on Plan G costs, carrier comparisons, enrollment, and switching plans. Written by a licensed independent broker.",
  alternates: { canonical: `${SITE_URL}/hub` },
  openGraph: {
    title: "Medicare Guides | MedicareYourself",
    description:
      "Straightforward Medicare guides on Plan G costs, carrier comparisons, enrollment, and switching plans. Written by a licensed independent broker.",
  },
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: "https://www.medicareyourself.com",
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "Medicare Guides",
      item: "https://www.medicareyourself.com/hub",
    },
  ],
};

/*
 * Edward Sturm Module 06 — Hub Page Information Architecture
 *
 * Hub page categories (H2s) group bottom-of-funnel landing pages.
 * Within each category, pages are ordered by search intent + volume
 * (highest-intent first, not alphabetically).
 *
 * Anchor text = the H1 of the target page.
 */

/* ── Category definitions ─────────────────────────────────────────────── */

interface HubLink {
  href: string;
  label: string; // anchor text = H1 of target page
}

interface HubCategory {
  heading: string;
  links: HubLink[];
}

/**
 * Static categories with manually-curated pages.
 * These are the existing, hand-built pages on the site.
 * As /services/[slug] pages are generated, they'll appear in the dynamic section below.
 */
const STATIC_CATEGORIES: HubCategory[] = [
  {
    heading: "Plan Comparisons",
    links: [
      { href: "/medicare-supplement/new-jersey/plan-g-vs-plan-n", label: "Medigap Plan G vs Plan N in New Jersey (2026): Which Is Better?" },
      { href: "/medicare-supplement/new-jersey/vs-medicare-advantage", label: "Medigap vs Medicare Advantage in New Jersey (2026)" },
      { href: "/learn/what-is-medigap", label: "What Is Medigap? Medicare Supplement Insurance Explained (2026)" },
      { href: "/learn/medicare-parts-explained", label: "Medicare Parts A, B, C, and D Explained Simply (2026)" },
    ],
  },
  {
    heading: "Costs & Pricing",
    links: [
      { href: "/medicare-supplement/new-jersey/cost", label: "How Much Does Medicare Cost in New Jersey in 2026?" },
      { href: "/learn/medicare-help-low-income", label: "Medicare Help for People on a Fixed Income (2026)" },
    ],
  },
  {
    heading: "Enrollment & Turning 65",
    links: [
      { href: "/medicare-supplement/new-jersey/turning-65", label: "Turning 65 in New Jersey: Your Complete Medicare Checklist (2026)" },
      { href: "/learn/how-to-sign-up-for-medicare", label: "How and When to Sign Up for Medicare (2026)" },
    ],
  },
  {
    heading: "Switching Plans",
    links: [
      { href: "/medicare-supplement/switch-carriers", label: "How to Switch Medicare Supplement Carriers Without Losing Coverage" },
    ],
  },
  {
    heading: "Medicare by State",
    links: [
      { href: "/medicare-supplement/new-jersey", label: "Best Medicare Supplement Plans in New Jersey (2026)" },
      { href: "/medicare-supplement/pennsylvania", label: "Best Medicare Supplement Plans in Pennsylvania (2026)" },
      { href: "/medicare-advantage/new-jersey", label: "Best Medicare Advantage Plans in New Jersey (2026)" },
    ],
  },
];

/**
 * Dynamically discovers all /services/[slug] pages at build time.
 * Each page.tsx is expected to export metadata with a title.
 * These are the compact-keyword BOF landing pages generated by build-compact-pages.js.
 */
function getDynamicHubPages(): HubLink[] {
  const hubDir = path.join(process.cwd(), "app", "services");
  const pages: HubLink[] = [];

  let entries: string[];
  try {
    entries = fs.readdirSync(hubDir);
  } catch {
    return pages;
  }

  for (const entry of entries) {
    const pagePath = path.join(hubDir, entry, "page.tsx");
    if (!fs.existsSync(pagePath)) continue;

    const source = fs.readFileSync(pagePath, "utf8");

    // Extract H1 from the page (preferred anchor text per Edward Module 06)
    const h1Match = source.match(/<h1[^>]*>([^<]+)<\/h1>/i);
    // Fallback to metadata title
    const titleMatch = source.match(/title:\s*"([^"]+)"/);

    const label = h1Match?.[1] || titleMatch?.[1]?.replace(/\s*\|.*$/, "") || entry.replace(/-/g, " ");

    pages.push({ href: `/services/${entry}`, label });
  }

  return pages;
}

export default function HubPage() {
  const dynamicPages = getDynamicHubPages();

  return (
    <>
      <SchemaMarkup schema={[breadcrumbSchema]} />

      {/* Breadcrumb */}
      <nav className="max-w-6xl mx-auto px-4 pt-4 text-sm text-gray-500">
        <Link href="/" className="hover:text-blue-600">
          Home
        </Link>
        <span className="mx-2">&rsaquo;</span>
        <span className="text-gray-900 font-medium">Medicare Guides</span>
      </nav>

      {/* Hero — H1 + 1-2 sentences intro (Edward Module 06) */}
      <section className="max-w-6xl mx-auto px-4 py-10">
        <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
          Medicare Guides
        </h1>
        <p className="text-lg text-gray-600 leading-relaxed max-w-3xl">
          We help Medicare beneficiaries find the right coverage with free,
          unbiased guidance from a licensed independent broker. Here are the
          most common topics people explore before choosing a plan:
        </p>
      </section>

      {/* Hub categories — H2 headings with BOF pages listed underneath */}
      <section className="max-w-6xl mx-auto px-4 pb-12 space-y-10">
        {STATIC_CATEGORIES.map((category) => (
          <div key={category.heading}>
            <h2 className="text-xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-200">
              {category.heading}
            </h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {category.links.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  className="block bg-white border border-gray-200 rounded-lg p-5 hover:border-blue-300 hover:shadow-md transition-all"
                >
                  <span className="font-semibold text-gray-900 text-sm leading-snug">
                    {link.label}
                  </span>
                </Link>
              ))}
            </div>
          </div>
        ))}

        {/* Dynamic hub/[slug] pages — compact keyword BOF pages */}
        {dynamicPages.length > 0 && (
          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-200">
              More Medicare Guides
            </h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {dynamicPages.map((page) => (
                <Link
                  key={page.href}
                  href={page.href}
                  className="block bg-white border border-gray-200 rounded-lg p-5 hover:border-blue-300 hover:shadow-md transition-all"
                >
                  <span className="font-semibold text-gray-900 text-sm leading-snug">
                    {page.label}
                  </span>
                </Link>
              ))}
            </div>
          </div>
        )}
      </section>

      {/* Bottom CTA (Edward Module 06: generic call to action button) */}
      <section className="bg-blue-700 text-white py-10 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-2xl font-bold mb-3">
            Have a Medicare Question Not Covered Here?
          </h2>
          <p className="text-blue-100 mb-6 text-lg">
            Call Anthony directly for a free, no-pressure conversation about
            your Medicare options.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <PhoneCTA size="lg" label="Call 855-559-1700" />
            <Link
              href="/quote"
              className="inline-flex items-center justify-center gap-2 px-6 py-3 bg-white/10 hover:bg-white/20 border border-white/30 text-white font-semibold rounded-lg transition-colors"
            >
              Get a Free Quote
            </Link>
          </div>
          <p className="text-blue-200 text-sm mt-4">
            Free &middot; Independent &middot; Licensed in NJ and 34 states
          </p>
        </div>
      </section>
    </>
  );
}
