/**
 * sanitize-content.js
 * Strips AI-generated content markers from TSX/MDX page files.
 *
 * Two passes:
 *  1. HTML/JSX marker removal — data-*, docs-internal-guid, Mso* classes,
 *     AI comment markers, meta generator tags
 *  2. Prose phrase replacement — known AI signature phrases swapped for
 *     plain, direct alternatives
 *
 * Usage:
 *   node sanitize-content.js app/hub/some-page/page.tsx
 *   node sanitize-content.js              (scans all pages under app/)
 *
 * Writes changes in place and logs a summary of every substitution made.
 */

const fs = require("fs");
const path = require("path");

// ---------------------------------------------------------------------------
// Path validation — prevent path traversal attacks on the CLI arg
// ---------------------------------------------------------------------------
const REPO_ROOT = path.resolve(__dirname, "..");
const APP_DIR = path.join(REPO_ROOT, "app");

function safeResolvePath(inputPath) {
  const resolved = path.resolve(REPO_ROOT, inputPath);
  if (!resolved.startsWith(APP_DIR + path.sep) && resolved !== APP_DIR) {
    throw new Error(`Path outside allowed app/ directory: ${inputPath}`);
  }
  return resolved;
}

// ---------------------------------------------------------------------------
// Discover page files
// ---------------------------------------------------------------------------
function discoverPages(dir, results = []) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
      discoverPages(full, results);
    } else if (entry.name === "page.tsx" || entry.name.endsWith(".mdx")) {
      results.push(full);
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// Pass 1 — HTML/JSX marker removal
// ---------------------------------------------------------------------------

/**
 * Strip AI-editor and clipboard-paste data attributes from JSX strings.
 * Targets:
 *   data-start, data-end           — token position markers (ChatGPT/Gemini paste)
 *   data-pm-slice, data-pm-doc-index, data-pm-node-type — ProseMirror clipboard
 *   data-block-id, data-content-id — Notion / Jasper exports
 *   data-token-index, data-index-in-node, data-path-to-node — Gemini export
 *   data-sourcepos                 — Markdown-to-HTML converters in AI pipelines
 */
const AI_DATA_ATTRS = [
  "data-start",
  "data-end",
  "data-pm-slice",
  "data-pm-doc-index",
  "data-pm-node-type",
  "data-block-id",
  "data-content-id",
  "data-token-index",
  "data-index-in-node",
  "data-path-to-node",
  "data-sourcepos",
];

/**
 * Remove listed data-* attributes from JSX/HTML content.
 * Matches: data-attr="value"  data-attr={expr}  data-attr (boolean)
 */
function stripDataAttributes(source) {
  let result = source;
  let count = 0;
  for (const attr of AI_DATA_ATTRS) {
    // Quoted string value: data-attr="..."
    const quotedRe = new RegExp(`\\s*${attr}="[^"]*"`, "g");
    const jsxExprRe = new RegExp(`\\s*${attr}=\\{[^}]*\\}`, "g"); // JSX expr
    const booleanRe = new RegExp(`\\s+${attr}(?=[\\s/>])`, "g"); // boolean attr
    const before = result.length;
    result = result.replace(quotedRe, "").replace(jsxExprRe, "").replace(booleanRe, "");
    if (result.length !== before) count++;
  }
  return { source: result, count };
}

/**
 * Remove Google Docs internal GUID IDs: id="docs-internal-guid-XXXX"
 */
function stripDocsGuid(source) {
  const re = /\s*id="docs-internal-guid-[a-f0-9-]+"/g;
  const matches = source.match(re) || [];
  return { source: source.replace(re, ""), count: matches.length };
}

/**
 * Remove Microsoft Office paste artifacts:
 *   class="MsoNormal", class="MsoBodyText", mso-* inline styles, <o:p> tags
 */
function stripMsoArtifacts(source) {
  let result = source;
  let count = 0;

  // Mso class names in className attributes
  const msoClassRe = /\s*className="Mso[^"]*"/g;
  const msoClassMatches = result.match(msoClassRe) || [];
  result = result.replace(msoClassRe, "");
  count += msoClassMatches.length;

  // mso-* inline style properties
  const msoStyleRe = /\s*mso-[a-z-]+:[^;";]+;?/g;
  const msoStyleMatches = result.match(msoStyleRe) || [];
  result = result.replace(msoStyleRe, "");
  count += msoStyleMatches.length;

  // <o:p> Office paragraph tags
  const oPRe = /<\/?o:p>/g;
  const oPMatches = result.match(oPRe) || [];
  result = result.replace(oPRe, "");
  count += oPMatches.length;

  return { source: result, count };
}

/**
 * Strip HTML comment markers left by AI content tools:
 *   <!-- Generated by ... -->
 *   <!-- AI_BLOCK_START --> ... <!-- AI_BLOCK_END -->
 *   <!-- wp:paragraph {"ai":true} -->
 */
function stripAiComments(source) {
  let result = source;
  let count = 0;

  const patterns = [
    /<!--\s*Generated by[^-]*-->/gi,
    /<!--\s*AI_BLOCK_(START|END)\s*-->/gi,
    /<!--\s*wp:[^\n]*"ai"\s*:\s*true[^-]*-->/gi,
    /<!--\s*AI[_\s]generated[^-]*-->/gi,
  ];

  for (const re of patterns) {
    const matches = result.match(re) || [];
    result = result.replace(re, "");
    count += matches.length;
  }

  return { source: result, count };
}

/**
 * Audit (but don't auto-remove) meta generator/ai tags — log warnings instead.
 * Removing these from TSX metadata objects needs manual review.
 */
function auditMetaTags(source, filePath) {
  const warnings = [];
  if (/name:\s*["']generator["']/.test(source)) {
    warnings.push(`  ⚠  generator meta tag found — review manually`);
  }
  if (/name:\s*["']ai-generated["']/.test(source)) {
    warnings.push(`  ⚠  ai-generated meta tag found — review manually`);
  }
  return warnings;
}

// ---------------------------------------------------------------------------
// Pass 2 — AI signature phrase replacement
// ---------------------------------------------------------------------------

/**
 * Each entry: [pattern (regex or string), replacement, label]
 * Replacements are plain, direct alternatives that fit Medicare content.
 * Patterns use word boundaries where needed to avoid false matches.
 */
const PHRASE_REPLACEMENTS = [
  // Opening filler phrases
  [/\bIt(?:'s| is) (?:important|critical|essential) to note that\b/gi, "", "filler:important-to-note"],
  [/\bIt(?:'s| is) worth noting that\b/gi, "", "filler:worth-noting"],
  [/\bIt(?:'s| is) important to understand that\b/gi, "", "filler:important-to-understand"],
  [/\bFrom a broader perspective[,.]?\s*/gi, "", "filler:broader-perspective"],
  [/\bGenerally speaking[,.]?\s*/gi, "", "filler:generally-speaking"],
  [/\bAt its core[,.]?\s*/gi, "", "filler:at-its-core"],
  [/\bIn the realm of\b/gi, "In", "filler:realm-of"],
  [/\bIn today's (?:ever-evolving|fast-changing|complex) (?:landscape|world|environment)\b/gi, "Today", "filler:todays-landscape"],
  [/\bNavigate the complexities of\b/gi, "Understand", "filler:navigate-complexities"],
  [/\bUnlock the potential of\b/gi, "Use", "filler:unlock-potential"],
  [/\bEmbark on your (?:journey|path)\b/gi, "Get started", "filler:embark-journey"],
  [/\bA testament to\b/gi, "Evidence of", "filler:testament"],

  // Mechanical transition overuse
  [/\bHaving said that[,.]?\s*/gi, "", "transition:having-said-that"],
  [/\bThat being said[,.]?\s*/gi, "", "transition:that-being-said"],
  [/\bWith that in mind[,.]?\s*/gi, "", "transition:with-that-in-mind"],
  [/\bNeedless to say[,.]?\s*/gi, "", "transition:needless-to-say"],
  [/\bIt is worth emphasizing that\b/gi, "", "transition:worth-emphasizing"],

  // Closing filler
  [/\bIn conclusion[,.]?\s*/gi, "", "filler:in-conclusion"],
  [/\bIn summary[,.]?\s*/gi, "", "filler:in-summary"],
  [/\bTo summarize[,.]?\s*/gi, "", "filler:to-summarize"],
  [/\bOverall, it is clear that\b/gi, "Overall,", "filler:overall-clear"],

  // AI vocabulary — Tier 1 (strongest signals)
  [/\bdelve(?:s|d|ing)?\b/gi, "look", "vocab:delve"],
  [/\btapestry\b/gi, "mix", "vocab:tapestry"],
  [/\bintricacies\b/gi, "details", "vocab:intricacies"],
  [/\bintricate(?:ly)?\b/gi, "complex", "vocab:intricate"],
  [/\bmeticulous(?:ly)?\b/gi, "careful", "vocab:meticulous"],
  [/\bmultifaceted\b/gi, "complex", "vocab:multifaceted"],
  [/\bunderscore(?:s|d)?\b/gi, "highlight", "vocab:underscore"],
  [/\binterplay\b/gi, "interaction", "vocab:interplay"],
  [/\bpivotal\b/gi, "key", "vocab:pivotal"],
  [/\bgarner(?:s|ed|ing)?\b/gi, "get", "vocab:garner"],
  [/\bfoster(?:s|ed|ing)?\b/gi, "support", "vocab:foster"],
  [/\bbolster(?:s|ed|ing)?\b/gi, "strengthen", "vocab:bolster"],
  [/\bseamless(?:ly)?\b/gi, "smooth", "vocab:seamless"],
  [/\brobust\b/gi, "strong", "vocab:robust"],

  // Medicare-specific AI clichés
  [/\bNavigate the Medicare landscape\b/gi, "Understand your Medicare options", "medicare:navigate-landscape"],
  [/\bEmpowering seniors to make informed decisions\b/gi, "Helping seniors choose the right plan", "medicare:empowering-seniors"],
  [/\bEnsuring peace of mind\b/gi, "Reducing out-of-pocket risk", "medicare:peace-of-mind"],
  [/\bSeamless transition to Medicare\b/gi, "Enrolling in Medicare", "medicare:seamless-transition"],
  [/\bComprehensive coverage for your needs\b/gi, "Coverage that matches your situation", "medicare:comprehensive-coverage"],
];

function replacePhrases(source) {
  let result = source;
  const changes = [];

  for (const [pattern, replacement, label] of PHRASE_REPLACEMENTS) {
    const matches = result.match(pattern) || [];
    if (matches.length > 0) {
      result = result.replace(pattern, replacement);
      changes.push({ label, count: matches.length, examples: matches.slice(0, 2) });
    }
  }

  return { source: result, changes };
}

// ---------------------------------------------------------------------------
// Main sanitize function
// ---------------------------------------------------------------------------

function sanitizeFile(filePath) {
  const source = fs.readFileSync(filePath, "utf8");
  let current = source;
  const report = { file: filePath, changes: [], warnings: [] };

  // Pass 1 — HTML markers
  const dataResult = stripDataAttributes(current);
  current = dataResult.source;
  if (dataResult.count > 0) report.changes.push(`Stripped ${dataResult.count} AI data attributes`);

  const guidResult = stripDocsGuid(current);
  current = guidResult.source;
  if (guidResult.count > 0) report.changes.push(`Removed ${guidResult.count} Google Docs GUID IDs`);

  const msoResult = stripMsoArtifacts(current);
  current = msoResult.source;
  if (msoResult.count > 0) report.changes.push(`Cleaned ${msoResult.count} MSO Office artifacts`);

  const commentResult = stripAiComments(current);
  current = commentResult.source;
  if (commentResult.count > 0) report.changes.push(`Removed ${commentResult.count} AI comment markers`);

  // Meta tag audit (warnings only — no auto-edit on metadata objects)
  const metaWarnings = auditMetaTags(current, filePath);
  report.warnings.push(...metaWarnings);

  // Pass 2 — prose phrases
  const phraseResult = replacePhrases(current);
  current = phraseResult.source;
  for (const change of phraseResult.changes) {
    report.changes.push(`Replaced [${change.label}] x${change.count}`);
  }

  // Write if changed
  if (current !== source) {
    fs.writeFileSync(filePath, current, "utf8");
    report.modified = true;
  } else {
    report.modified = false;
  }

  return report;
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function run() {
  const arg = process.argv[2];
  let files = [];

  if (arg) {
    // Single file mode
    let resolved;
    try {
      resolved = safeResolvePath(arg);
    } catch (e) {
      console.error(`Error: ${e.message}`);
      process.exit(1);
    }
    if (!fs.existsSync(resolved)) {
      console.error(`File not found: ${resolved}`);
      process.exit(1);
    }
    files = [resolved];
  } else {
    // Scan all pages
    files = discoverPages(APP_DIR);
    console.log(`Scanning ${files.length} page files under app/\n`);
  }

  let modifiedCount = 0;
  let cleanCount = 0;

  for (const filePath of files) {
    const report = sanitizeFile(filePath);
    const rel = path.relative(REPO_ROOT, filePath);

    if (report.modified) {
      modifiedCount++;
      console.log(`✓ ${rel}`);
      for (const change of report.changes) console.log(`    ${change}`);
    } else {
      cleanCount++;
      if (files.length === 1) console.log(`✓ ${rel} — no changes needed`);
    }

    for (const warning of report.warnings) {
      console.log(`  ${rel}${warning}`);
    }
  }

  if (files.length > 1) {
    console.log(`\nDone. ${modifiedCount} files sanitized, ${cleanCount} already clean.`);
  }
}

run();
